$ip_address = "192.168.11.20"
$interface = "enp2s0"
$script = <<-'SCRIPT'
  sudo apt-get update
  sudo apt-get install -y nfs-kernel-server
  sudo mkdir /share
  sudo chown nobody:nogroup /share
  echo "/share *(rw,sync,no_subtree_check)" | sudo tee -a /etc/exports
  sudo exportfs -ar
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.define "nfs" do |nfs|
    nfs.vm.hostname = "nfs"
    nfs.vm.network "public_network", ip: $ip_address, bridge: $interface
    nfs.vm.provider "virtualbox" do |vb|
      vb.name = "nfs"
      vb.memory = "2048"
      vb.cpus = "2"
    end
    nfs.vm.provision "shell", inline: $script
  end
end
