Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "public_network", ip: "192.168.11.10", bridge: "enp2s0"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.memory = "4096"
      vb.cpus = "4"
    end
  end
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "worker"
    worker.vm.network "public_network", ip: "192.168.11.11", bridge: "enp2s0"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "worker"
      vb.memory = "4096"
      vb.cpus = "4"
    end
    worker.vm.disk :disk, size: "10GB", name: "extra_storage"
  end
  config.vm.define "worker2" do |worker2|
    worker2.vm.box = "ubuntu/focal64"
    worker2.vm.hostname = "worker2"
    worker2.vm.network "public_network", ip: "192.168.11.12", bridge: "enp2s0"
    worker2.vm.provider "virtualbox" do |vb|
      vb.name = "worker2"
      vb.memory = "4096"
      vb.cpus = "4"
    end
    worker2.vm.disk :disk, size: "10GB", name: "extra_storage"
  end
  config.vm.define "worker3" do |worker3|
    worker3.vm.box = "ubuntu/focal64"
    worker3.vm.hostname = "worker3"
    worker3.vm.network "public_network", ip: "192.168.11.13", bridge: "enp2s0"
    worker3.vm.provider "virtualbox" do |vb|
      vb.name = "worker3"
      vb.memory = "4096"
      vb.cpus = "4"
    end
    worker3.vm.disk :disk, size: "10GB", name: "extra_storage"
  end
end