Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "public_network", ip: "192.168.11.10", bridge: "enp2s0"
    master.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.memory = "2048"
      vb.cpus = "4"
    end
  end
  config.vm.define "worker" do |worker|
    worker.vm.hostname = "worker"
    worker.vm.network "public_network", ip: "192.168.11.11", bridge: "enp2s0"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "worker"
      vb.memory = "2048"
      vb.cpus = "4"
    end
  end
end