Resources:
  # VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

  # Subnet 
  PublicSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: ap-northeast-1a
      Tags:
        - Key: Name
          Value: PublicSubnet01

  PrivateSubnet01:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: ap-northeast-1a
      Tags:
        - Key: Name
          Value: PrivateSubnet01

  # # InternetGateway
  # MyIGW:
  #   Type: AWS::EC2::InternetGateway
  #   Properties:
  #     Tags:
  #       - Key: Name
  #         Value: MyIGW

  # AttachGateway:
  #   Type: AWS::EC2::VPCGatewayAttachment
  #   Properties:
  #     VpcId: !Ref MyVPC
  #     InternetGatewayId: !Ref MyIGW

  # Route Table
  RoutePublicSubnet:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: RoutePublicSubnet

  RoutePrivateSubnet:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: RoutePrivateSubnet

  # # Route
  # RoutePublic: 
  #   Type: AWS::EC2::Route
  #   Properties:
  #     RouteTableId: !Ref RoutePublicSubnet
  #     DestinationCidrBlock: 0.0.0.0/0
  #     GatewayId: !Ref MyIGW

  RoutePrivate: 
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RoutePrivateSubnet
      DestinationCidrBlock: 192.168.1.0/24
      GatewayId: vgw-008778b66f8f0cd8b

  # Route Table Association
  RouteTableAssocPublic01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet01
      RouteTableId: !Ref RoutePublicSubnet

  RouteTableAssocPrivate01:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet01
      RouteTableId: !Ref RoutePrivateSubnet

Outputs:
  MyVPC:
    Value: !Ref MyVPC
    Export:
      Name: MyVPC

  PublicSubnet01:
    Value: !Ref PublicSubnet01
    Export:
      Name: PublicSubnet01

  PrivateSubnet01:
    Value: !Ref PrivateSubnet01
    Export:
      Name: PrivateSubnet01
